### ISSUE TITLE
Expose CRC32C module

### ISSUE THREAD

**Issue by fkm3** [kim/snappy-framing#1]
Hi. I'm looking for an implementation of CRC32C in haskell. What do you think of exposing the one in this repo (or splitting it into a separate cabal package)?

**Comment by kim** [comment]
I think I stole the implementation here from some blog post of @ekmett, which I now can't seem to find anymore due to lack of proper attribution (shame on me). The implementation is in "pure" Haskell, which is not as fast as could be.

What's your use case? I'd say it would only really be worth releasing a separate package if some effort was put into making it fast (which will involve going through the FFI).

**Comment by fkm3** [comment]
It would be used as part of a haskell implementation of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/record_writer.h. I'd use tensorflow's implementation of crc32c, but wrapping C++ seems like a pain.

Optimizations can always come later if it turns out to be useful enough.

**Comment by kim** [comment]
I uploaded a version to hackage which exposes the module. Please let me know how it goes wrt throughput.

**Comment by fkm3** [comment]
Thanks!

**Comment by ekmett** [comment]
https://www.schoolofhaskell.com/user/edwardk/parallel-crc is probably the article.

**Comment by ekmett** [comment]
https://www.schoolofhaskell.com/user/edwardk/cellular-automata/part-2 is the straightforward forward-only CRC machine, the `parallel-crc` article builds a monoid for crc calculation by tracking the number of bits n seen so far as `x^n` as an extra number, which is sufficient to make it a monoid.

**Comment by kim** [comment]
Thanks. I remember having read both articles in search for an existing crc32c implementation in Haskell, but how I arrived at my (arguably much more conventional) implementation remains lost from my memory.
